global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "pgmoneta"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:5001"] # Assuming pgmoneta runs on host port 5001
